package consts

const (
	AuroraInterSectionUpdate   = "aurora.UpdateInterSection"
	AuroraInterSectionDelete   = "aurora.DeleteInterSection"
	AuroraPileNoStorageUpdate  = "aurora.UpdatePileNoStorage"
	AuroraPileNoStorageDelete  = "aurora.DeletePileNoStorage"
	AuroraSubjectUpdate        = "aurora.UpdateSubject"
	AuroraSubjectDelete        = "aurora.DeleteSubject"
	AuroraAlignmentUpdate      = "aurora.UpdateAlignment"
	AuroraAlignmentDelete      = "aurora.DeleteAlignment"
	AuroraChainUpdate          = "aurora.UpdateChain"
	AuroraChainDelete          = "aurora.DeleteChain"
	AuroraRoadsurfaceUpdate    = "aurora.UpdateRoadsurface"
	AuroraRoadsurfaceDelete    = "aurora.DeleteRoadsurface"
	AuroraBridgeUpdate         = "aurora.UpdateBridge"
	AuroraBridgeDelete         = "aurora.DeleteBridge"
	AuroraBridgePartUpdate     = "aurora.UpdateBridgePart"
	AuroraBridgePartDelete     = "aurora.DeleteBridgePart"
	AuroraCulvertUpdate        = "aurora.UpdateCulvert"
	AuroraCulvertDelete        = "aurora.DeleteCulvert"
	AuroraCulvertPartUpdate    = "aurora.UpdateCulvertPart"
	AuroraCulvertPartDelete    = "aurora.DeleteCulvertPart"
	AuroraOverBridgeUpdate     = "aurora.UpdateOverBridge"
	AuroraOverBridgeDelete     = "aurora.DeleteOverBridge"
	AuroraOverBridgePartUpdate = "aurora.UpdateOverBridgePart"
	AuroraOverBridgePartDelete = "aurora.DeleteOverBridgePart"
	AuroraTunnelUpdate         = "aurora.UpdateTunnel"
	AuroraTunnelDelete         = "aurora.DeleteTunnel"
	AuroraTunnelPartUpdate     = "aurora.UpdateTunnelPart"
	AuroraTunnelPartDelete     = "aurora.DeleteTunnelPart"
	AuroraConstructZoneUpdate  = "aurora.UpdateConstructZone"
	AuroraConstructZoneDelete  = "aurora.DeleteConstructZone"

	PushMessageToKafka = "aurora.PushMessageToKafka"
)
